version: '3.8'

services:
  nextjs-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
      - .env.local
    networks:
      - job-search-network

networks:
  job-search-network:
    driver: bridge
